
export const Constant={
    authenticFood:{src:['./images/partPage/vetnamFood1.png',
                        './images/partPage/vetnamFood2.png',
                        './images/partPage/vetnamFood3.png',
                        './images/partPage/vetnamFood4.png',
                        './images/partPage/vetnamFood5.png',
                        './images/partPage/vetnamFood6.png',
                        './images/partPage/vetnamFood7.png']},
    fiveStar:{src:['./images/partPage/fiveStar1.png',
                    './images/partPage/fiveStar2.png',
                    './images/partPage/fiveStar3.png',
                    './images/partPage/fiveStar4.png',
                    './images/partPage/fiveStar5.png',
                    './images/partPage/fiveStar6.png',
                    './images/partPage/fiveStar7.png',
                    './images/partPage/fiveStar8.png',
                    './images/partPage/fiveStar9.png',
                    './images/partPage/fiveStar10.png',
                    './images/partPage/fiveStar11.png',
                    './images/partPage/fiveStar12.png']},

    onlineCookery:{src:['./images/partPage/onlineCookery1.png',
                        './images/partPage/onlineCookery2.png',
                        './images/partPage/onlineCookery3.png',
                        './images/partPage/onlineCookery4.png',
                        './images/partPage/onlineCookery5.png',
                        './images/partPage/onlineCookery6.png']},
    tryCook:{src:['./images/partPage/tryCook1.png',
                    './images/partPage/tryCook2.png',
                    './images/partPage/tryCook3.png',
                    './images/partPage/tryCook4.png',
                    './images/partPage/tryCook5.png',
                    './images/partPage/tryCook6.png',
                    './images/partPage/tryCook7.png']},
    orderOnline:{src:['./images/partPage/orderOnline.png']},
    profile1:{src:['./images/partPage/ChefYellow.svg',
                    './images/partPage/chefImg1.png',
                    './images/partPage/cookDetail1_1.png',
                    './images/partPage/cookDetail1_2.png',
                    './images/partPage/cookDetail1_3.png',]},
    profile2:{src:['./images/partPage/ChefRed.svg',
                    './images/partPage/chefImg2.png',
                    './images/partPage/cookDetail2_1.png',
                    './images/partPage/cookDetail2_2.png',
                    './images/partPage/cookDetail2_3.png',]},
    orderConfirmation:{
        src:['./images/partPage/orderConfirmation1.png',
             './images/partPage/orderConfirmation2.png',
             './images/partPage/orderConfirmation3.png',
             './images/partPage/orderConfirmation4.png',
             './images/partPage/orderConfirmation5.png',
             './images/partPage/orderConfirmation6.png']
    }


}
