// cart count action
export const ADDCARTICON = 'ADDCARTICON';
// user info action
export const CHANGEEMAIL = 'CHANGEEMAIL';
export const CHANGEUSERNAME = 'CHANGEUSERNAME';
export const CHANGEID = 'CHANGEID';
// another user info actioin
export const CHANGECHEFID = 'CHANGECHEFID';
export const CHANGECHEFNAME = 'CHANGECHEFNAME';
export const CHANGECHEFEMAIL = 'CHANGECHEFEMAIL';
export const CHANGEAVATARIMG = 'CHANGEAVATARIMG';
export const CHANGEADDRESS = 'CHANGEADDRESS';
export const CHANGECITY = 'CHANGECITY';
export const CHANGECOUNTRY = 'CHANGECOUNTRY';
export const CHANGEPOSTCODE = 'CHANGEPOSTCODE';
// per food action
export const CHANGEPERID = 'CHANGEPERID';
export const CHANGEPERIDFLAG = 'CHANGEPERIDFLAG';
export const CHANGEPERPORTION = 'CHANGEPERPORTION';
export const CHANGEPERIMG = 'CHANGEPERIMG';
export const CHANGEPERCOST = 'CHANGEPERCOST';
export const CHANGEPERQUANTITY = 'CHANGEPERQUANTITY';
export const CHANGEPERCUISINENAME = 'CHANGEPERCUISINENAME';
export const CHANGEAUTHEN = 'CHANGEAUTHEN';
export const CHANGECOMMENTTOCHEF = 'CHANGECOMMENTTOCHEF';
export const CHANGEPERRATING = 'CHANGEPERRATING';
// cart info start
export const CHANGECARTFLAG = 'CHANGECARTFLAG';
export const CHANGEORDERDATA = 'CHANGEORDERDATA';
export const CHANGEORDERIMGDATA = 'CHANGEORDERIMGDATA';
// cart info end